
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: discord
  name: bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      restartPolicy: Always
      containers:
        - name: bot
          image: aiarena/discordbot:2024.12.22-14.15
          env:
            - name: SECRETS
              value: "/etc/secrets"
          volumeMounts:
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: config
 